name = "accident-claims-scotland-enquiries"
main = "workers/enquiry.js"
compatibility_date = "2026-06-19"
workers_dev = true

[[send_email]]
name = "ENQUIRY_EMAIL"
destination_address = "rckgregory66@gmail.com"
allowed_sender_addresses = ["enquiries@accident-claims-scotland.com"]
